name: Trigger auto deployment for synthetica-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/synthetica-api-AutoDeployTrigger-9216172d-12fb-4777-9ce1-a103201f7a74.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SYNTHETICAAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SYNTHETICAAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SYNTHETICAAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: Dockerfile
          registryUrl: syntheicaregistry-gkc0bafwe2h4h5ct.azurecr.io
          registryUsername: ${{ secrets.SYNTHETICAAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SYNTHETICAAPI_REGISTRY_PASSWORD }}
          containerAppName: synthetica-api
          resourceGroup: synthetica-rg
          imageToBuild: syntheicaregistry-gkc0bafwe2h4h5ct.azurecr.io/synthetica-api:${{ github.sha }}


