name: Trigger auto deployment for synthetica-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/synthetica-web-AutoDeployTrigger-3fdff1d6-69ee-4be6-a721-ddb00508708f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SYNTHETICAWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SYNTHETICAWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SYNTHETICAWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: syntheicaregistry-gkc0bafwe2h4h5ct.azurecr.io
          registryUsername: ${{ secrets.SYNTHETICAWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SYNTHETICAWEB_REGISTRY_PASSWORD }}
          containerAppName: synthetica-web
          resourceGroup: synthetica-rg
          imageToBuild: syntheicaregistry-gkc0bafwe2h4h5ct.azurecr.io/synthetica-web:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


